### PR TITLE
Merge JS

### PR DESCRIPTION
**Pull request by sumantguha**

### CODE REVIEW

**Review by hschafer — COMMENTED** [review]
All of this looks good! But please delete the `.DS_Store` files before I approve :)

**Comment by hschafer** [comment]
Added a commit that I just added to the main branch to make it build on your pull request too :)

**Comment by sumantguha** [comment]
Removed the .DS_Store files!

**Comment by hschafer** [comment]
Looks great to me! Will merge it in now :)

**Review by hschafer — APPROVED** [review]
Looks good to me!

**Pull request merged**
